export default function head(){
    return(
        <>
        <title>Zohaib Khan</title>
        <meta content="width=device-width, initial-scale=1" name="viewport"/>
        <meta name="description" content="Generated by c"/>
        </>
    )
}